[package]
name = "rust-crates-index-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
codegen-units = 1


[dependencies]
crates-index = "0.18.9"
reqwest = { version = "0.11.12", features = ["stream"] }
tokio = { version = "1.21.1", features = ["full"] }
flate2 = "1.0.24"
serde = { version = "1.0.145", features = ["derive"] }
cargo_toml = "0.12.4"
rayon = "1.5.3"
futures = "0.3.24"
num_cpus = "1.13.1"
backoff = { version = "0.4.0", features = ["tokio"] }
async-compression = { version = "0.3.14", features = ["tokio", "gzip"] }
tokio-util = { version = "0.7.4", features = ["io"] }
futures-util = "0.3.24"
async-tar = "0.4.2"
async-std = "1.12.0"
tracing-log = "0.1.3"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = [
    "env-filter",
    "std",
    "registry",
    "fmt",
    "json"
] }
indicatif = "0.17.1"
systemstat = "0.2.1"
bytes = "1.2.1"
futures-core = "0.3.24"
thiserror = "1.0.36"
