[package]
name = "rust-crates-index-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
codegen-units = 1


[dependencies]
crates-index = "0.18.7"
reqwest = { version = "0.11.10", features = ["stream"] }
tokio = { version = "1.18.0", features = ["full"] }
flate2 = "1.0.22"
serde = { version = "1.0.136", features = ["derive"] }
cargo_toml = "0.11.5"
rayon = "1.5.2"
futures = "0.3.21"
num_cpus = "1.13.1"
backoff = { version = "0.4.0", features = ["tokio"] }
async-compression = { version = "0.3.12", features = ["tokio", "gzip"] }
tokio-util = { version = "0.7.1", features = ["io"] }
futures-util = "0.3.21"
async-tar = "0.4.2"
async-std = "1.11.0"
tracing-log = "0.1.3"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = [
    "env-filter",
    "std",
    "registry",
    "fmt",
    "json"
] }
indicatif = "0.16.2"
