[package]
name = "rust-crates-index-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
codegen-units = 1


[dependencies]
bytes = "1.4.0"
crates-index = "0.19.7"
serde = { version = "1.0.158", features = ["derive"] }
reqwest = { version = "0.11.15", features = ["stream"] }
tokio = { version = "1.26.0", features = ["rt", "macros"] }
flate2 = "1.0.24"
rayon = "1.7.0"
futures = "0.3.24"
num_cpus = "1.15.0"
backoff = { version = "0.4.0", features = ["tokio"] }
async-compression = { version = "0.3.14", features = ["tokio", "gzip"] }
tokio-util = { version = "0.7.7", features = ["io"] }
futures-util = "0.3.24"
async-tar = "0.4.2"
async-std = "1.12.0"
tracing-log = "0.1.3"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.16", features = [
    "env-filter",
    "std",
    "registry",
    "fmt",
    "json",
] }
systemstat = "0.2.3"
indicatif = "0.17.3"
futures-core = "0.3.24"
thiserror = "1.0.40"
cargo_toml = "0.15.2"
